In [1]:
import numpy as np
import pandas as pd
from tabulate import tabulate

In [2]:
df = pd.read_csv('../CleanedData/betas.csv', delimiter = ',')

In [36]:
df.head()

,method,d,v,session,P1,P2,P3,P4,P5,P6,...,P5792,P5793,P5794,P5795,P5796,P5797,P5799,P5800,P5801,P5802
0,history,55,1,hs6bovtz,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,history,55,3,3cda8qpn,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,history,55,9,bvpj37io,-0.026604,NaN,NaN,0.026534,NaN,-0.010334,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,history,148,1,ehaxc7lu,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,history,148,3,ck291lk5,NaN,NaN,NaN,NaN,NaN,0.395292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
len(df.columns)

5605

In [42]:
df1 = df.iloc[:, range(4, 5605)]

In [43]:
df1.head()

,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,...,P5792,P5793,P5794,P5795,P5796,P5797,P5799,P5800,P5801,P5802
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.068205,NaN,0.112137,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-0.026604,NaN,NaN,0.026534,NaN,-0.010334,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,0.395292,NaN,NaN,NaN,0.353573,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df['mean'] = df1.mean(axis=1)

In [47]:
df

,method,d,v,session,P1,P2,P3,P4,P5,P6,...,P5793,P5794,P5795,P5796,P5797,P5799,P5800,P5801,P5802,mean
0,history,55,1,hs6bovtz,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.061315
1,history,55,3,3cda8qpn,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.129440
2,history,55,9,bvpj37io,-0.026604,NaN,NaN,0.026534,NaN,-0.010334,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.009096
3,history,148,1,ehaxc7lu,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.108550
4,history,148,3,ck291lk5,NaN,NaN,NaN,NaN,NaN,0.395292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.313899
5,history,148,9,2hxe3g0w,0.248030,NaN,NaN,0.152173,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.250036
6,history,403,1,9bbkjlye,0.374438,NaN,NaN,NaN,NaN,0.048585,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.249687
7,history,403,3,5du4txa7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.431889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.452133
8,history,403,9,spw8qdcd,NaN,NaN,NaN,0.421942,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.393480
9,history,1097,1,huyygtho,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.524079,NaN,NaN,NaN,NaN,NaN,0.310620
10,history,1097,1,z0rvh02v,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.240625,NaN,NaN,0.286628
11,history,1097,3,hhb0if6e,0.696901,NaN,NaN,0.693910,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.556360
12,history,1097,9,wv4xujg7,NaN,NaN,NaN,NaN,NaN,0.516149,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.465552
13,max,55,1,aebicytb,NaN,0.011605,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.019550
14,max,55,3,094p61xp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.115992
15,max,55,9,8c80yyxl,NaN,NaN,0.230740,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.298749,NaN,NaN,0.010967,NaN,0.105847
16,max,148,1,78wuly7l,NaN,NaN,0.093149,NaN,NaN,NaN,...,0.093605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.093149,0.010440
17,max,148,3,u2sxnl2p,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.082771,NaN,NaN,NaN,0.316826
18,max,148,9,mf57hnwb,NaN,0.205623,NaN,NaN,0.196900,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.189427
19,max,403,1,1r17post,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.453237
20,max,403,1,6c4s02ki,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.368733
21,max,403,1,e8vv9575,NaN,NaN,0.647005,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.446613
22,max,403,3,ua2230ux,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.368437,NaN,NaN,NaN,NaN,NaN,NaN,0.134703
23,max,403,9,1xyev3dj,NaN,-0.090728,NaN,NaN,-0.081387,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065027
24,max,1097,1,7yqp8bxc,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.526338
25,max,1097,1,q5brhgnz,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.313622
26,max,1097,3,2x6km84z,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.177590
27,max,1097,3,ud5vo371,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.591702
28,max,1097,9,lh7wb36v,NaN,0.218853,0.914886,NaN,0.759524,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.354290